version: "3.6"
services:
  eshopwebmvc:
    environment:
    - ConfigController__Enabled=false
    - Database__Provider=SqlServer
    image: docker.io/sixeyed/eshopwebmvc
    ports:
    - ${eshopwebmvc.port}:80
    secrets:
    - source: db-connection-string
      target: /app/config/db-connection-string
secrets:
  db-connection-string:
    external: true
